#ifndef BOMB_FLIP_CONTROLS_H
#define BOMB_FLIP_CONTROLS_H

#include <riv.h>

enum {
    CONTROL_REVEAL = RIV_GAMEPAD_A1,
    CONTROL_SCANNER = RIV_GAMEPAD_A2,
    CONTROL_FOLD_MENU = RIV_GAMEPAD_SELECT,
    CONTROL_FOLD_MENU_ALT = RIV_GAMEPAD_R2,
    CONTROL_START = RIV_GAMEPAD_START,
    CONTROL_CHEAT_COMPLETE_LEVEL = RIV_GAMEPAD_R1
};

#endif
